### ISSUE TITLE
Add "Are you sure" configurations

### ISSUE THREAD

**Issue by zeplar-exe** [zeplar-exe/FsTag#5]
Configured for specific operations to ask the user if they want to carry it out. This will be displayed as a yes/no input like the following;

```shell
> fstag bulk delete --recycle
> Are you sure you want to delete 702 files in the 'test_session' session? (yes/no): y
...
```

The input will accept any form of yes (y, yes, Y, YES, etc), and anything else as no. This is defined on a command-by-command basis, usually providing session information alongside the result of the operation.

**Comment by mohammed0xff** [comment]
willing to help.

**Comment by zeplar-exe** [comment]
@mohammed0xff I appreciate it. Make sure to read CONTRIBUTING.md, then clone/fork and make a PR.

**Comment by zeplar-exe** [comment]
Completed via 04e9946
